import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
      <Link href="/">首页</Link>
      <Link href="/test">测试</Link>
      <Link href="/software">软件</Link>
        </nav>
        {children}</body>
    </html>
  )
}
